# Generated by Django 4.2 on 2023-05-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.PositiveIntegerField(verbose_name='Внешний id пользователя'),
        ),
    ]
