# Generated by Django 4.2 on 2023-05-04 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
